SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `liber_test` DEFAULT CHARACTER SET utf8 ;
USE `liber_test` ;

CREATE TABLE IF NOT EXISTS `liber_test`.`recipes` (
  RECIPE_NAME VARCHAR(255) PRIMARY KEY NOT NULL ,
  PREPARATION_METHOD VARCHAR(255) NOT NULL)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `liber_test`.`ingredients` (
  ID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  INGREDIENT VARCHAR(255) NOT NULL ,
  RECIPE_NAME VARCHAR(255) NOT NULL,
  CONSTRAINT FK_INGREDIENTS_RECIPES FOREIGN KEY (RECIPE_NAME) REFERENCES `liber_test`.`recipes` (RECIPE_NAME))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `liber_test`.`recipe_metadata` (
  ID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PREPARATION_TIME_IN_MINUTES INT(4),
  NUMBER_OF_SERVINGS INT(4),
  ADDITIONAL_NOTES VARCHAR(255),
  RECIPE_NAME VARCHAR(255) NOT NULL,
  CONSTRAINT FK_METADATA_RECIPES FOREIGN KEY (RECIPE_NAME) REFERENCES `liber_test`.`recipes` (RECIPE_NAME))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `liber_test`.`categories` (
  ID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CATEGORY_NAME VARCHAR(255) NOT NULL ,
  RECIPE_NAME VARCHAR(255) NOT NULL,
  CONSTRAINT FK_CATEGORIES_RECIPES FOREIGN KEY (RECIPE_NAME) REFERENCES `liber_test`.`recipes` (RECIPE_NAME))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;