/*
 * This file is generated by jOOQ.
 */
package com.techx.generatedsources.entity.tables.records;


import com.techx.generatedsources.entity.tables.RecipeMetadata;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecipeMetadataRecord extends UpdatableRecordImpl<RecipeMetadataRecord> implements Record5<Integer, Integer, Integer, String, String> {

    private static final long serialVersionUID = 1731367729;

    /**
     * Setter for <code>recipe_metadata.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>recipe_metadata.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>recipe_metadata.PREPARATION_TIME_IN_MINUTES</code>.
     */
    public void setPreparationTimeInMinutes(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>recipe_metadata.PREPARATION_TIME_IN_MINUTES</code>.
     */
    public Integer getPreparationTimeInMinutes() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>recipe_metadata.NUMBER_OF_SERVINGS</code>.
     */
    public void setNumberOfServings(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>recipe_metadata.NUMBER_OF_SERVINGS</code>.
     */
    public Integer getNumberOfServings() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>recipe_metadata.ADDITIONAL_NOTES</code>.
     */
    public void setAdditionalNotes(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>recipe_metadata.ADDITIONAL_NOTES</code>.
     */
    public String getAdditionalNotes() {
        return (String) get(3);
    }

    /**
     * Setter for <code>recipe_metadata.RECIPE_NAME</code>.
     */
    public void setRecipeName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>recipe_metadata.RECIPE_NAME</code>.
     */
    public String getRecipeName() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return RecipeMetadata.RECIPE_METADATA.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return RecipeMetadata.RECIPE_METADATA.PREPARATION_TIME_IN_MINUTES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return RecipeMetadata.RECIPE_METADATA.NUMBER_OF_SERVINGS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return RecipeMetadata.RECIPE_METADATA.ADDITIONAL_NOTES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return RecipeMetadata.RECIPE_METADATA.RECIPE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getPreparationTimeInMinutes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getNumberOfServings();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getAdditionalNotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getRecipeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPreparationTimeInMinutes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getNumberOfServings();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAdditionalNotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getRecipeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecipeMetadataRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecipeMetadataRecord value2(Integer value) {
        setPreparationTimeInMinutes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecipeMetadataRecord value3(Integer value) {
        setNumberOfServings(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecipeMetadataRecord value4(String value) {
        setAdditionalNotes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecipeMetadataRecord value5(String value) {
        setRecipeName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecipeMetadataRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RecipeMetadataRecord
     */
    public RecipeMetadataRecord() {
        super(RecipeMetadata.RECIPE_METADATA);
    }

    /**
     * Create a detached, initialised RecipeMetadataRecord
     */
    public RecipeMetadataRecord(Integer id, Integer preparationTimeInMinutes, Integer numberOfServings, String additionalNotes, String recipeName) {
        super(RecipeMetadata.RECIPE_METADATA);

        set(0, id);
        set(1, preparationTimeInMinutes);
        set(2, numberOfServings);
        set(3, additionalNotes);
        set(4, recipeName);
    }
}
