/*
 * This file is generated by jOOQ.
 */
package com.techx.generatedsources.entity.tables.records;


import com.techx.generatedsources.entity.tables.Recipes;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecipesRecord extends UpdatableRecordImpl<RecipesRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 809219034;

    /**
     * Setter for <code>recipes.RECIPE_NAME</code>.
     */
    public void setRecipeName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>recipes.RECIPE_NAME</code>.
     */
    public String getRecipeName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>recipes.PREPARATION_METHOD</code>.
     */
    public void setPreparationMethod(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>recipes.PREPARATION_METHOD</code>.
     */
    public String getPreparationMethod() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Recipes.RECIPES.RECIPE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Recipes.RECIPES.PREPARATION_METHOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getRecipeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPreparationMethod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getRecipeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPreparationMethod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecipesRecord value1(String value) {
        setRecipeName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecipesRecord value2(String value) {
        setPreparationMethod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecipesRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RecipesRecord
     */
    public RecipesRecord() {
        super(Recipes.RECIPES);
    }

    /**
     * Create a detached, initialised RecipesRecord
     */
    public RecipesRecord(String recipeName, String preparationMethod) {
        super(Recipes.RECIPES);

        set(0, recipeName);
        set(1, preparationMethod);
    }
}
