/*
 * This file is generated by jOOQ.
 */
package com.techx.generatedsources.entity;


import com.techx.generatedsources.entity.tables.Categories;
import com.techx.generatedsources.entity.tables.Ingredients;
import com.techx.generatedsources.entity.tables.RecipeMetadata;
import com.techx.generatedsources.entity.tables.Recipes;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CATEGORIES_FK_CATEGORIES_RECIPES = Indexes0.CATEGORIES_FK_CATEGORIES_RECIPES;
    public static final Index CATEGORIES_PRIMARY = Indexes0.CATEGORIES_PRIMARY;
    public static final Index INGREDIENTS_FK_INGREDIENTS_RECIPES = Indexes0.INGREDIENTS_FK_INGREDIENTS_RECIPES;
    public static final Index INGREDIENTS_PRIMARY = Indexes0.INGREDIENTS_PRIMARY;
    public static final Index RECIPE_METADATA_FK_METADATA_RECIPES = Indexes0.RECIPE_METADATA_FK_METADATA_RECIPES;
    public static final Index RECIPE_METADATA_PRIMARY = Indexes0.RECIPE_METADATA_PRIMARY;
    public static final Index RECIPES_PRIMARY = Indexes0.RECIPES_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CATEGORIES_FK_CATEGORIES_RECIPES = Internal.createIndex("FK_CATEGORIES_RECIPES", Categories.CATEGORIES, new OrderField[] { Categories.CATEGORIES.RECIPE_NAME }, false);
        public static Index CATEGORIES_PRIMARY = Internal.createIndex("PRIMARY", Categories.CATEGORIES, new OrderField[] { Categories.CATEGORIES.ID }, true);
        public static Index INGREDIENTS_FK_INGREDIENTS_RECIPES = Internal.createIndex("FK_INGREDIENTS_RECIPES", Ingredients.INGREDIENTS, new OrderField[] { Ingredients.INGREDIENTS.RECIPE_NAME }, false);
        public static Index INGREDIENTS_PRIMARY = Internal.createIndex("PRIMARY", Ingredients.INGREDIENTS, new OrderField[] { Ingredients.INGREDIENTS.ID }, true);
        public static Index RECIPE_METADATA_FK_METADATA_RECIPES = Internal.createIndex("FK_METADATA_RECIPES", RecipeMetadata.RECIPE_METADATA, new OrderField[] { RecipeMetadata.RECIPE_METADATA.RECIPE_NAME }, false);
        public static Index RECIPE_METADATA_PRIMARY = Internal.createIndex("PRIMARY", RecipeMetadata.RECIPE_METADATA, new OrderField[] { RecipeMetadata.RECIPE_METADATA.ID }, true);
        public static Index RECIPES_PRIMARY = Internal.createIndex("PRIMARY", Recipes.RECIPES, new OrderField[] { Recipes.RECIPES.RECIPE_NAME }, true);
    }
}
