/*
 * This file is generated by jOOQ.
 */
package com.techx.generatedsources.entity;


import com.techx.generatedsources.entity.tables.Categories;
import com.techx.generatedsources.entity.tables.Ingredients;
import com.techx.generatedsources.entity.tables.RecipeMetadata;
import com.techx.generatedsources.entity.tables.Recipes;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>categories</code>.
     */
    public static final Categories CATEGORIES = com.techx.generatedsources.entity.tables.Categories.CATEGORIES;

    /**
     * The table <code>ingredients</code>.
     */
    public static final Ingredients INGREDIENTS = com.techx.generatedsources.entity.tables.Ingredients.INGREDIENTS;

    /**
     * The table <code>recipe_metadata</code>.
     */
    public static final RecipeMetadata RECIPE_METADATA = com.techx.generatedsources.entity.tables.RecipeMetadata.RECIPE_METADATA;

    /**
     * The table <code>recipes</code>.
     */
    public static final Recipes RECIPES = com.techx.generatedsources.entity.tables.Recipes.RECIPES;
}
